// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-realtimemap/app/transport/mqtt/internal/conf"
	"kratos-realtimemap/app/transport/mqtt/internal/server"
	"kratos-realtimemap/app/transport/mqtt/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	transportMqttService := service.NewTransportMqttService(logger)
	grpcServer := server.NewGRPCServer(confServer, logger, transportMqttService)
	mqttServer := server.NewMQTTServer(confServer, logger, transportMqttService)
	kafkaServer := server.NewKafkaServer(confServer, logger, transportMqttService)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, mqttServer, kafkaServer, registrar)
	return app, func() {
	}, nil
}
