trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:0
    timeout: 1s
  grpc:
    addr: 0.0.0.0:0
    timeout: 1s
  mqtt:
    addr: ssl://mqtt.hsl.fi:8883
  kafka:
    addrs:
      - 127.0.0.1:9092
data:
